### ISSUE TITLE
rabbitmq_recent_history_exchange-1.0.1-rmq3.2.4.ez is broken

### ISSUE THREAD

**Issue by latypoff** [rabbitmq/rabbitmq-recent-history-exchange#14]
I've recently tried to install that binary and it fails, rabbitmq says:

=ERROR REPORT==== 9-Apr-2015::11:05:13 ===
Problem reading some plugins: [{"/usr/lib/rabbitmq/lib/rabbitmq_server-3.2.4/sbin/../plugins/rabbitmq_recent_history_exchange-1.0.1-rmq3.2.4.ez",
                                {invalid_ez,einval}}]
1.0.0 is also broken

$ uname -a
Linux ip-172-30-1-180 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

$ dpkg -s rabbitmq-server
Package: rabbitmq-server
Status: install ok installed
Priority: extra
Section: net
Installed-Size: 4753
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Version: 3.2.4-1
Depends: erlang-nox (>= 1:13.b.3) | esl-erlang, adduser, logrotate
Conffiles:
 /etc/logrotate.d/rabbitmq-server ddaa633357e5f6ff9d7970c6d0a9acd8
 /etc/default/rabbitmq-server 7cc5216f193f6be1cb32c45021197b39
 /etc/init.d/rabbitmq-server 5d49d9839503d8912b13dc1123498257
Description: AMQP server written in Erlang
 RabbitMQ is an implementation of AMQP, the emerging standard for high
 performance enterprise messaging. The RabbitMQ server is a robust and
 scalable implementation of an AMQP broker.
Original-Maintainer: RabbitMQ Team <packaging@rabbitmq.com>
Homepage: http://www.rabbitmq.com/

**Comment by videlalvaro** [comment]
Please install the version provided here http://www.rabbitmq.com/community-plugins.html

**Comment by latypoff** [comment]
09.04.2015, 18:20, "Alvaro Videla" <notifications@github.com>:Please install the version provided here http://www.rabbitmq.com/community-plugins.html Thanks! It works!  Sent from my iPhone  > On Apr 9, 2015, at 12:27 PM, latypoff <notifications@github.com> wrote: >  > I've recently tried to install that binary and it fails, rabbitmq says: >  > =ERROR REPORT==== 9-Apr-2015::11:05:13 === > Problem reading some plugins: [{"/usr/lib/rabbitmq/lib/rabbitmq_server-3.2.4/sbin/../plugins/rabbitmq_recent_history_exchange-1.0.1-rmq3.2.4.ez", > {invalid_ez,einval}}] > 1.0.0 is also broken >  > $ uname -a > Linux ip-172-30-1-180 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux >  > $ cat /etc/os-release > NAME="Ubuntu" > VERSION="14.04.2 LTS, Trusty Tahr" > ID=ubuntu > ID_LIKE=debian > PRETTY_NAME="Ubuntu 14.04.2 LTS" > VERSION_ID="14.04" > HOME_URL="http://www.ubuntu.com/" > SUPPORT_URL="http://help.ubuntu.com/" > BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/" >  > — > Reply to this email directly or view it on GitHub. > —Reply to this email directly or view it on GitHub.   -- br, Denis F. Latypoff.

**Comment by michaelklishin** [comment]
There were new builds since then, closing assuming that they no longer have such issues.

**Comment by michaelklishin** [comment]
Also, the docs should mention what RabbitMQ server versions are supported.
