### ISSUE TITLE
[Bug] On binding to exchange messages are delivered in reverese order

### ISSUE THREAD

**Issue by Badmoonz** [rabbitmq/rabbitmq-recent-history-exchange#29]
Line 121, Msgs list should be reversed before forwarded through destination exchange

**Comment by lukebakken** [comment]
Please open a pull request against this file if this issue still exists:

https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbitmq_recent_history_exchange/src/rabbit_exchange_type_recent_history.erl
