### ISSUE TITLE
[Feature] Possibility which recover historical exchange after restart rabbitMq.

### ISSUE THREAD

**Issue by tvvister** [rabbitmq/rabbitmq-recent-history-exchange#32]
After some experiments with restart rabbitMq I've observed no recovered messages in historical exchange. So it would be better experience if persistance of messages in historical exchange will appear.

**Comment by tvvister** [comment]
After some experiments with restart rabbitMq I've observed no recovered messages in historical exchange. So it would be better experience if persistance of messages in historical exchange will appear.

**Comment by lukebakken** [comment]
Currently a [RAM table is used](https://github.com/rabbitmq/rabbitmq-recent-history-exchange/blob/master/src/rabbit_exchange_type_recent_history.erl#L124-L131).

At this point there is not enough interest to add persistence to cached messages.
